/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serial;

import javax.swing.JSplitPane;

/**
 *
 * @author John
 */
public class SplitTerminal extends JSplitPane {

    /**
     * Creates new form SplitTerminal
     * @param terminal The terminal log to be placed
     * @param dataSet The line chart to be placed
     * @param leftToRight Determines whether the components are added from left-to-right (true) or right to left (false)
     */
    public SplitTerminal(TermLog terminal, LineChart dataSet, boolean leftToRight) {
        initComponents();
        if(leftToRight){
            add(terminal, LEFT);
            add(dataSet, RIGHT);
        } else {
            add(terminal, RIGHT);
            add(dataSet, LEFT);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDividerLocation(200);
        setDividerSize(5);
        setResizeWeight(0.25);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
